# Generated by Django 2.2.28 on 2023-04-14 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_club', models.UUIDField()),
                ('nombre', models.CharField(max_length=256)),
                ('logo', models.BinaryField()),
                ('color1', models.SmallIntegerField()),
                ('color2', models.SmallIntegerField()),
                ('color3', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disciplina', models.UUIDField()),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jugador', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.SmallIntegerField()),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_club', to='torneos.Clubes')),
                ('disciplina1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_disciplina1', to='torneos.Disciplinas')),
                ('disciplina2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_disciplina2', to='torneos.Disciplinas')),
                ('disciplina3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_disciplina3', to='torneos.Disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='JugadoresDisciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.SmallIntegerField()),
                ('rankeo', models.SmallIntegerField()),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadoresdisciplinas_id_disciplina', to='torneos.Disciplinas')),
                ('id_jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadoresdisciplinas_id_jugador', to='torneos.Jugadores')),
            ],
        ),
    ]
