# Generated by Django 2.2.28 on 2023-04-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubes',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='clubes_disciplinas', to='torneos.Disciplinas'),
        ),
    ]
