# Generated by Django 2.2.28 on 2023-04-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_clubes_disciplinas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='disciplina1',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='disciplina2',
        ),
        migrations.RemoveField(
            model_name='jugadores',
            name='disciplina3',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, related_name='jugadores_disciplinas', to='torneos.Disciplinas'),
        ),
    ]
