# Generated by Django 2.2.28 on 2023-04-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_auto_20230414_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='id_jugador',
        ),
    ]
