# Generated by Django 2.2.28 on 2023-04-14 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_remove_jugadores_id_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubes',
            name='id_club',
        ),
        migrations.RemoveField(
            model_name='disciplinas',
            name='id_disciplina',
        ),
    ]
