# Generated by Django 2.2.28 on 2023-04-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0005_auto_20230414_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('modalidad', models.BooleanField()),
                ('clubes', models.ManyToManyField(blank=True, related_name='torneos_clubes', to='torneos.Clubes')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torneos_disciplina', to='torneos.Disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='TorneosJugadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneosjugadores_jugador', to='torneos.Jugadores')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneosjugadores_torneo', to='torneos.Torneos')),
            ],
        ),
    ]
