# Generated by Django 2.2.28 on 2023-04-14 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0006_torneos_torneosjugadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('estructura', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='torneosjugadores',
            name='horario_jugador',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='torneos',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torneos_formato', to='torneos.Formatos'),
        ),
    ]
