# Generated by Django 2.2.28 on 2023-04-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0008_torneos_inter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadores',
            name='club',
        ),
        migrations.RemoveField(
            model_name='torneos',
            name='clubes',
        ),
        migrations.DeleteModel(
            name='Clubes',
        ),
    ]
