# Generated by Django 2.2.28 on 2023-04-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0009_auto_20230415_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JugadoresDisciplinas',
        ),
    ]
