# Generated by Django 2.2.28 on 2023-04-15 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0011_auto_20230415_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneosjugadores',
            name='jugador',
        ),
        migrations.DeleteModel(
            name='Jugadores',
        ),
    ]
