# Generated by Django 2.2.28 on 2023-04-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0012_auto_20230415_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TorneosJugadores',
        ),
    ]
