# Generated by Django 2.2.28 on 2023-04-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0013_delete_torneosjugadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Torneos',
        ),
    ]
