# Generated by Django 2.2.28 on 2023-04-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230412_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_user',
        ),
    ]
